version: '3.8'

services:
  paukemon:
    build: .
    container_name: paukemon-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/paukemon
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_GENERATE_DDL=true
    volumes:
      - paukemon_data:/app/data
    restart: unless-stopped

volumes:
  paukemon_data:
    driver: local 